import type { CountryConfig } from '../../types';

export const CA_CONFIG: CountryConfig = {
  code: 'ca',
  flag: '🇨🇦',
  label: 'Canada',
  groups: [
    {
      key: 'food_produce',
      label: 'Produce',
      order: 1,
      sections: [
        {
          key: 'produce',
          label: 'Produce',
          keywords: [
            'apple', 'banana', 'orange', 'grape', 'berries', 'strawberry', 'blueberry', 'raspberry', 'blackberry',
            'melon', 'pineapple', 'pear', 'peach', 'plum', 'kiwi', 'mango', 'lemon', 'lime', 'avocado', 'tomato',
            'potato', 'sweet potato', 'carrot', 'onion', 'red onion', 'spring onion', 'green onion', 'garlic',
            'pepper', 'chili', 'broccoli', 'cauliflower', 'cucumber', 'lettuce', 'salad', 'spinach', 'kale',
            'cabbage', 'mushroom', 'zucchini', 'eggplant', 'celery', 'leek', 'ginger', 'herbs', 'parsley', 'basil',
            'corn', 'beet', 'beets', 'turnip', 'rutabaga', 'squash',
          ],
        },
      ],
    },
    {
      key: 'food_fresh',
      label: 'Fresh Foods',
      order: 2,
      sections: [
        {
          key: 'bakery_counter',
          label: 'Bakery',
          keywords: [
            'fresh bread', 'bread', 'roll', 'bagel', 'bun', 'croissant', 'wrap', 'tortilla', 'cake', 'muffin',
            'cookie', 'cookies', 'pie', 'donut', 'doughnut', 'baguette', 'pastry', 'sourdough', 'loaf', 'focaccia',
            'naan', 'bannock',
          ],
        },
        {
          key: 'butcher_counter',
          label: 'Meat Counter',
          keywords: [
            'butcher', 'beef roast', 'steak', 'ribeye', 'sirloin', 'ground beef', 'beef', 'pork chop', 'pork loin',
            'chicken breast', 'chicken thighs', 'whole chicken', 'turkey breast', 'lamb chops', 'bacon', 'sausage',
            'veal', 'venison',
          ],
        },
        {
          key: 'seafood_counter',
          label: 'Seafood Counter',
          keywords: [
            'seafood', 'fish', 'salmon fillet', 'cod fillet', 'tuna steak', 'shrimp', 'prawns', 'crab', 'lobster',
            'scallops', 'tilapia', 'halibut', 'pickerel', 'whole fish',
          ],
        },
        {
          key: 'deli_counter',
          label: 'Deli / Prepared Foods',
          keywords: [
            'deli', 'cold cuts', 'sliced ham', 'turkey slices', 'roast beef slices', 'pastrami', 'salami',
            'rotisserie chicken', 'prepared salad', 'potato salad', 'macaroni salad', 'prepared foods',
            'smoked meat', 'montreal smoked meat',
          ],
        },
        {
          key: 'chilled_milk_juice_cream',
          label: 'Dairy / Refrigerated',
          keywords: [
            'milk', 'whole milk', '2% milk', 'skim milk', 'oat milk', 'almond milk', 'soy milk', 'gold milk',
            'blue milk', 'green milk', 'red milk', 'juice', 'orange juice', 'apple juice', 'smoothie', 'cream',
            'half and half', 'whipped cream', 'butter', 'yogurt', 'yoghurt', 'cheese', 'cheddar', 'mozzarella',
            'parmesan', 'eggs', 'egg', 'cream cheese', 'sour cream', 'buttermilk', 'kefir', 'cottage cheese',
          ],
        },
        {
          key: 'chilled_cooked_meat',
          label: 'Packaged Lunch Meat',
          keywords: ['ham', 'ham slices', 'turkey slices', 'roast beef slices', 'chicken slices', 'pepperoni', 'salami pack'],
        },
        {
          key: 'chilled_fresh_meat',
          label: 'Fresh Meat',
          keywords: ['minced beef', 'ground beef', 'ground turkey', 'sausages', 'burgers', 'chicken breast', 'chicken thighs', 'pork chops', 'bacon', 'lamb chops'],
        },
        {
          key: 'chilled_ready_meals',
          label: 'Prepared Meals',
          keywords: ['ready meal', 'prepared meal', 'lasagna', 'lasagne', 'frozen dinner', 'microwave meal', 'meal kit', 'family meal', 'poutine'],
        },
      ],
    },
    {
      key: 'food_freezers',
      label: 'Frozen Foods',
      order: 3,
      sections: [
        {
          key: 'frozen_veg',
          label: 'Frozen Vegetables',
          keywords: ['frozen veg', 'frozen vegetables', 'frozen peas', 'frozen sweetcorn', 'frozen corn', 'frozen broccoli', 'frozen spinach', 'frozen green beans', 'frozen mixed veg', 'frozen mixed vegetables', 'frozen carrots', 'frozen cauliflower', 'frozen edamame', 'frozen mushrooms', 'frozen peppers', 'frozen onions'],
        },
        {
          key: 'frozen_ice_cream',
          label: 'Ice Cream & Frozen Treats',
          keywords: ['ice cream', 'icecream', 'ice-cream', 'gelato', 'sorbet', 'frozen yogurt', 'frozen yoghurt', 'frozen dessert', 'popsicle', 'popsicles', 'ice pop', 'ice pops', 'fudgsicle', 'creamsicle', 'ice cream cones', 'ice cream sandwich', 'ice cream sandwiches', 'drumstick cones', 'ben and jerrys', 'ben and jerry\'s', 'haagen dazs', 'häagen-dazs'],
        },
        {
          key: 'frozen_fruit',
          label: 'Frozen Fruit',
          keywords: ['frozen fruit', 'frozen berries', 'frozen mixed berries', 'summer fruits', 'frozen summer fruits', 'frozen mango', 'frozen pineapple', 'frozen strawberries', 'frozen blueberries', 'frozen raspberries', 'frozen blackberries', 'frozen cherries', 'frozen peaches', 'frozen banana', 'smoothie mix', 'smoothie fruit'],
        },
        {
          key: 'frozen_meals',
          label: 'Frozen Meals',
          keywords: ['frozen pizza', 'frozen meal', 'frozen meals', 'frozen lasagna', 'frozen lasagne', 'frozen fries', 'fries', 'waffles', 'frozen waffles', 'hash brown', 'hash browns', 'fish sticks', 'chicken nuggets', 'frozen chicken nuggets', 'frozen burgers', 'frozen sausage', 'frozen garlic bread', 'garlic bread', 'frozen onion rings', 'onion rings', 'frozen burrito', 'frozen burritos', 'frozen dumplings', 'frozen potstickers', 'frozen pizza rolls', 'frozen fish', 'frozen shrimp', 'frozen prawns', 'perogies', 'pierogi', 'frozen perogies', 'frozen pierogi'],
        },
      ],
    },
    {
      key: 'food_pantry',
      label: 'Pantry & Grocery',
      order: 4,
      sections: [
        {
          key: 'cereal',
          label: 'Cereal Aisle',
          keywords: [
            'cereal',
            'breakfast cereal',
            'corn flakes',
            'cornflakes',
            'frosted flakes',
            'cheerios',
            'honey nut cheerios',
            'froot loops',
            'fruit loops',
            'rice krispies',
            'cocoa krispies',
            'shreddies',
            'shredded wheat',
            'mini wheats',
            'raisin bran',
            'granola',
            'muesli',
            'oatmeal',
            'instant oatmeal',
            'oats',
            'porridge oats',
            'bran flakes',
            'special k',
            'honey bunches of oats',
            'vector cereal',
          ],
        },
        {
          key: 'pantry',
          label: 'Pantry Staples',
          keywords: [
            'pantry', 'canned goods', 'canned food', 'canned tomatoes', 'beans', 'rice', 'quinoa', 'couscous',
            'soup', 'broth', 'stock', 'sauce', 'tomato sauce', 'pasta sauce', 'jarred sauce', 'peanut butter', 'jam',
            'jelly', 'honey', 'syrup', 'maple syrup', 'flour', 'sugar', 'baking powder',
            'baking soda', 'oil', 'olive oil', 'vinegar', 'salt', 'pepper', 'seasoning', 'coffee', 'tea',
          ],
        },
        {
          key: 'alcohol',
          label: 'Alcohol',
          keywords: [
            'alcohol',
            'alcoholic drinks',
            'booze',
            'beer',
            'lager',
            'ale',
            'stout',
            'ipa',
            'wine',
            'red wine',
            'white wine',
            'rose wine',
            'rosé wine',
            'prosecco',
            'champagne',
            'cava',
            'sparkling wine',
            'cider',
            'hard cider',
            'fruit cider',
            'whisky',
            'whiskey',
            'scotch',
            'bourbon',
            'rye whiskey',
            'irish whiskey',
            'jack daniels',
            'jack daniel\'s',
            'jack daniels whiskey',
            'jack daniel\'s whiskey',
            'jack daniels honey',
            'jack daniel\'s honey',
            'jack daniels fire',
            'jack daniel\'s fire',
            'jack daniels apple',
            'jack daniel\'s apple',
            'jack and coke',
            'rum',
            'vodka',
            'gin',
            'tequila',
            'brandy',
            'cognac',
            'liqueur',
            'baileys',
            'jagermeister',
            'jägermeister',
            'malibu',
            'archers',
            'sambuca',
            'kopparberg',
            'kopparberg cider',
            'kopparberg strawberry lime',
            'kopparberg strawberry and lime',
            'kopparberg mixed fruit',
            'kopparberg pear',
            'kopparberg mixed fruit tropical',
            'kopparberg strawberry pineapple',
            'kopparberg strawberry and pineapple',
            'kopparberg mango',
            'kopparberg raspberry',
            'kopparberg cherry',
            'kopparberg blueberry lime',
            'kopparberg blueberry and lime',
            'kopparberg rhubarb',
            'kopparberg sweet vintage apple',
            'kopparberg spiced apple',
            'kopparberg winter punch',
            'kopparberg alcohol free',
            'kopparberg non alcoholic',
            'kopparberg alcohol free strawberry lime',
            'kopparberg alcohol free strawberry and lime',
            'kopparberg alcohol free mixed fruit',
            'kopparberg alcohol free pear',
            'kopparberg gin',
            'kopparberg strawberry lime gin',
            'kopparberg strawberry and lime gin',
            'kopparberg passionfruit orange gin',
            'kopparberg passionfruit and orange gin',
            'kopparberg vodka',
            'kopparberg strawberry lime vodka',
            'kopparberg strawberry and lime vodka',
            'kopparberg lemon vodka',
            'kopparberg gin lemonade',
            'kopparberg gin and lemonade',
            'kopparberg strawberry lime gin lemonade',
            'kopparberg strawberry and lime gin and lemonade',
            'rekorderlig',
            'rekorderlig cider',
            'rekorderlig strawberry lime',
            'rekorderlig strawberry and lime',
            'rekorderlig wild berries',
            'rekorderlig mango raspberry',
            'rekorderlig mango and raspberry',
            'rekorderlig passionfruit',
            'rekorderlig peach raspberry',
            'rekorderlig peach and raspberry',
            'rekorderlig pineapple kiwi',
            'rekorderlig pineapple and kiwi',
            'rekorderlig blood orange',
            'rekorderlig pink lemon',
            'rekorderlig watermelon citrus',
            'rekorderlig watermelon and citrus',
            'rekorderlig blackberry blackcurrant',
            'rekorderlig blackberry and blackcurrant',
            'rekorderlig pear apple',
            'rekorderlig pear and apple',
            'rekorderlig non alcoholic',
            'rekorderlig non-alcoholic',
            'rekorderlig alcohol free',
          ],
        },
        {
          key: 'pasta',
          label: 'Pasta',
          keywords: [
            'pasta', 'spaghetti', 'bucatini', 'linguine', 'fettuccine', 'capellini', 'angel hair', 'penne',
            'rigatoni', 'fusilli', 'rotini', 'macaroni', 'elbows', 'cavatappi', 'manicotti', 'farfalle', 'bowties',
            'orecchiette', 'little ears', 'radiatore', 'orzo', 'ravioli', 'tortellini', 'gnocchi',
          ],
        },
        {
          key: 'snacks',
          label: 'Snacks & Candy',
          keywords: [
            'snacks', 'chips', 'crisps', 'crackers', 'pretzels', 'cookies', 'biscuits', 'candy', 'chocolate',
            'granola bar', 'granola bars', 'protein bar', 'nuts', 'trail mix', 'popcorn', 'tortilla chips',
            'ketchup chips', 'all dressed chips',
          ],
        },
        {
          key: 'drinks',
          label: 'Drinks',
          keywords: [
            'drinks', 'soda', 'soft drink', 'sparkling water', 'water', 'juice', 'energy drink', 'sports drink',
            'coffee', 'tea', 'iced tea', 'lemonade', 'sports drinks', 'bottled water', 'iced coffee',
            'soft drinks', 'pop', 'cola', 'diet cola', 'zero cola', 'coke', 'coca cola', 'coca-cola', 'diet coke',
            'coke zero', 'zero coke', 'cherry coke', 'pepsi', 'diet pepsi', 'pepsi zero',
            'cherry pepsi', 'pepsi cherry', 'lime pepsi', 'pepsi lime', 'mango pepsi', 'pepsi mango',
            'tropical pepsi', 'pepsi tropical', 'lemon pepsi', 'pepsi lemon', 'cherry pepsi zero',
            'pepsi zero cherry', 'lime pepsi zero', 'pepsi zero lime', 'mango pepsi zero', 'pepsi zero mango',
            'tropical pepsi zero', 'pepsi zero tropical', 'lemon pepsi zero', 'pepsi zero lemon',
            'coke cherry', 'lime coke', 'coke lime', 'mango coke', 'coke mango', 'tropical coke',
            'coke tropical', 'lemon coke', 'coke lemon', 'cherry coke zero', 'coke zero cherry',
            'lime coke zero', 'coke zero lime', 'mango coke zero', 'coke zero mango', 'tropical coke zero',
            'coke zero tropical', 'lemon coke zero', 'coke zero lemon',
            'sprite', 'sprite zero', 'zero sprite', '7up', '7 up', 'starry', 'sierra mist',
            'fanta', 'orange pop', 'grape pop', 'root beer', 'dr pepper', 'dr. pepper', 'mountain dew',
            'mtn dew', 'ginger ale', 'tonic water', 'seltzer', 'club soda', 'la croix', 'bubly',
            'canada dry', 'crush', 'red bull', 'monster', 'gatorade', 'powerade',
          ],
        },
      ],
    },
    {
      key: 'non_food_general',
      label: 'Home, Health & Family',
      order: 5,
      sections: [
        {
          key: 'baby',
          label: 'Baby Care',
          keywords: ['baby', 'diapers', 'wipes', 'formula', 'baby food', 'pacifier', 'bottle', 'baby shampoo', 'nappies'],
        },
        {
          key: 'clothing',
          label: 'Clothing',
          keywords: ['t shirt', 't-shirt', 'socks', 'underwear', 'school uniform', 'baby clothes', 'jeans', 'pyjamas', 'pajamas'],
        },
        {
          key: 'household',
          label: 'Home / Household Goods',
          keywords: [
            'washing up liquid', 'detergent', 'fabric softener', 'garbage bags', 'trash bags', 'foil', 'plastic wrap',
            'baking paper', 'paper towels', 'bleach', 'sponges', 'surface cleaner', 'disinfectant', 'laundry',
            'dishwasher tablet', 'dishwasher tablets', 'rinse aid', 'rubber gloves', 'bedding', 'pillow', 'duvet',
            'plate', 'mug', 'pan', 'frying pan', 'storage box',
          ],
        },
        {
          key: 'health_beauty',
          label: 'Health & Beauty',
          keywords: [
            'acetaminophen', 'ibuprofen', 'toothpaste', 'toothbrush', 'shampoo', 'conditioner', 'soap', 'body wash',
            'deodorant', 'razor', 'toilet paper', 'shaving foam', 'mouthwash', 'hand soap', 'face wash',
            'sanitary', 'tampons', 'pads', 'skincare', 'moisturizer', 'vitamins', 'bandages',
          ],
        },
        {
          key: 'electrical',
          label: 'Electrical Goods',
          keywords: ['toaster', 'kettle', 'dvd', 'batteries', 'light bulb', 'headphones', 'extension cord', 'charger'],
        },
        {
          key: 'pet_supplies',
          label: 'Pet Supplies',
          keywords: ['cat food', 'dog food', 'litter', 'pet treats', 'bird seed', 'pet toy', 'pet shampoo'],
        },
        {
          key: 'seasonal',
          label: 'Seasonal Aisle',
          keywords: ['easter egg', 'easter eggs', 'christmas decorations', 'bbq', 'barbecue', 'summer toys', 'garden games', 'halloween', 'valentines', 'thanksgiving', 'pumpkin'],
        },
      ],
    },
  ],
};
