import type { CountryCode, CountryConfig, MeasurementUnitSystem, SectionKey } from '../../types';
import { UK_CONFIG } from './uk';
import { US_CONFIG } from './us';

type SectionKeywordAdditions = Partial<Record<SectionKey, string[]>>;
type LabelOverrides = Partial<Record<string, string>>;

type InternationalConfigOptions = {
  base: CountryConfig;
  code: CountryCode;
  flag: string;
  label: string;
  unitSystem?: MeasurementUnitSystem;
  groupLabels?: LabelOverrides;
  sectionLabels?: Partial<Record<SectionKey, string>>;
  keywords?: SectionKeywordAdditions;
};

const unique = (values: string[]) => [...new Set(values)];

const createInternationalConfig = ({
  base,
  code,
  flag,
  label,
  unitSystem = 'metric',
  groupLabels = {},
  sectionLabels = {},
  keywords = {},
}: InternationalConfigOptions): CountryConfig => ({
  ...base,
  code,
  flag,
  label,
  measurement: {
    unitSystem,
    displayMode: 'metric',
  },
  groups: base.groups.map((group) => ({
    ...group,
    label: groupLabels[group.key] ?? group.label,
    sections: group.sections.map((section) => ({
      ...section,
      label: sectionLabels[section.key] ?? section.label,
      keywords: unique([...section.keywords, ...(keywords[section.key] ?? [])]),
    })),
  })),
});

const MEXICO_GROUP_LABELS: LabelOverrides = {
  food_produce: 'Frutas y verduras',
  food_fresh: 'Frescos',
  food_freezers: 'Congelados',
  food_pantry: 'Abarrotes',
  non_food_general: 'Hogar y cuidado personal',
};

export const FR_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'fr',
  flag: '🇫🇷',
  label: 'France',
  groupLabels: {
    food_produce: 'Fruits et légumes',
    food_counters: 'Rayons frais',
    food_chillers: 'Frais et crèmerie',
    food_freezers: 'Surgelés',
    food_cupboard: 'Épicerie',
    non_food_general: 'Maison et soins personnels',
  },
  sectionLabels: {
    produce: 'Fruits et légumes',
    bakery_counter: 'Boulangerie',
    butcher_counter: 'Boucherie',
    fishmonger_counter: 'Poissonnerie',
    deli_counter: 'Charcuterie / Traiteur',
    chilled_milk_juice_cream: 'Crèmerie / Frais',
    chilled_cooked_meat: 'Viande cuite emballée',
    chilled_fresh_meat: 'Viande fraîche emballée',
    chilled_ready_meals: 'Plats préparés frais',
    baby_food: 'Alimentation bébé',
    cereal: 'Céréales et petit déjeuner',
    snacks: 'Snacks et apéritifs',
    frozen_veg: 'Légumes surgelés',
    frozen_ice_cream: 'Glaces et desserts glacés',
    frozen_fruit: 'Fruits surgelés',
    frozen_meals: 'Plats surgelés',
    tinned_jarred: 'Conserves et bocaux',
    sauces: 'Sauces et condiments',
    pantry: 'Produits d’épicerie',
    home_baking: 'Pâtisserie maison',
    cooking_ingredients: 'Épices, huiles et cuisine du monde',
    hot_drinks: 'Café, thé et boissons chaudes',
    drinks: 'Boissons',
    alcohol: 'Alcool',
    pasta: 'Pâtes',
    clothing: 'Vêtements',
    household: 'Maison et entretien',
    health_beauty: 'Pharmacie / Hygiène et beauté',
    baby: 'Bébé',
    electrical: 'Électricité',
    pet_supplies: 'Animaux',
    seasonal: 'Saisonnier',
  },
  keywords: {
    produce: ['pomme', 'banane', 'orange', 'fraise', 'framboise', 'myrtille', 'poire', 'pêche', 'raisin', 'citron', 'avocat', 'tomate', 'pomme de terre', 'carotte', 'oignon', 'ail', 'salade', 'concombre', 'poivron', 'courgette', 'aubergine', 'champignon', 'poireau', 'épinards'],
    bakery_counter: ['baguette', 'pain', 'pain complet', 'pain de mie', 'croissant', 'pain au chocolat', 'brioche', 'viennoiserie', 'chausson aux pommes'],
    butcher_counter: ['boucherie', 'boeuf', 'bœuf', 'poulet', 'porc', 'agneau', 'dinde', 'steak haché', 'saucisse', 'merguez', 'lardons'],
    fishmonger_counter: ['poisson', 'saumon', 'cabillaud', 'crevettes', 'thon', 'moules', 'truite', 'lieu noir', 'coquilles saint jacques'],
    deli_counter: ['charcuterie', 'jambon', 'jambon cru', 'saucisson', 'pâté', 'rillettes', 'terrine', 'traiteur', 'taboulé'],
    chilled_milk_juice_cream: ['lait', 'beurre', 'yaourt', 'fromage', 'emmental', 'comté', 'camembert', 'chèvre', 'crème fraîche', 'oeufs', 'œufs', 'jus frais'],
    cereal: ['céréales', 'muesli', 'granola', 'flocons avoine', 'porridge', 'biscottes'],
    frozen_veg: ['petits pois surgelés', 'haricots verts surgelés', 'légumes surgelés', 'épinards surgelés', 'frites surgelées'],
    frozen_ice_cream: ['glace', 'sorbet', 'cornets glacés', 'bâtonnets glacés'],
    frozen_fruit: ['fruits rouges surgelés', 'framboises surgelées', 'mangue surgelée'],
    frozen_meals: ['pizza surgelée', 'quiche surgelée', 'plats surgelés', 'poêlée surgelée'],
    tinned_jarred: ['conserve', 'haricots', 'pois chiches', 'tomates concassées', 'maïs', 'thon en boîte', 'cornichons', 'compote'],
    sauces: ['ketchup', 'mayonnaise', 'mayo', 'moutarde', 'moutarde de dijon', 'sauce barbecue', 'sauce soja', 'sauce piquante', 'sriracha', 'sauce tomate'],
    pantry: ['riz', 'semoule', 'lentilles', 'pâtes sèches', 'bouillon', 'sel', 'poivre', 'chips', 'biscuits apéritifs'],
    home_baking: ['farine', 'sucre', 'sucre glace', 'levure chimique', 'levure boulangère', 'pâte feuilletée', 'pépites chocolat'],
    cooking_ingredients: ['huile olive', 'huile d olive', 'huile tournesol', 'vinaigre', 'vinaigre balsamique', 'herbes de provence', 'paprika', 'cumin', 'curry'],
    hot_drinks: ['café', 'dosettes café', 'thé', 'tisane', 'chocolat chaud'],
    drinks: ['eau', 'eau gazeuse', 'limonade', 'sirop', 'orangina', 'oasis'],
    alcohol: ['vin rouge', 'vin blanc', 'rosé', 'champagne', 'cidre', 'pastis'],
    baby: ['couches', 'lingettes bébé', 'lait infantile'],
    household: ['lessive', 'liquide vaisselle', 'papier toilette', 'essuie tout', 'sacs poubelle'],
    health_beauty: ['dentifrice', 'shampoing', 'gel douche', 'déodorant'],
  },
});

export const DE_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'de',
  flag: '🇩🇪',
  label: 'Germany',
  groupLabels: {
    food_produce: 'Obst und Gemüse',
    food_counters: 'Frischetheken',
    food_chillers: 'Kühlregal',
    food_freezers: 'Tiefkühlkost',
    food_cupboard: 'Trockensortiment',
    non_food_general: 'Haushalt und Körperpflege',
  },
  sectionLabels: {
    produce: 'Obst und Gemüse',
    bakery_counter: 'Bäckerei',
    butcher_counter: 'Metzgerei / Fleischtheke',
    fishmonger_counter: 'Fischtheke',
    deli_counter: 'Wurst und Käse',
    chilled_milk_juice_cream: 'Molkereiprodukte / Kühlung',
    chilled_cooked_meat: 'Gekochtes Fleisch, verpackt',
    chilled_fresh_meat: 'Frischfleisch, verpackt',
    chilled_ready_meals: 'Fertiggerichte gekühlt',
    baby_food: 'Babynahrung',
    cereal: 'Müsli und Frühstück',
    snacks: 'Snacks und Süßwaren',
    frozen_veg: 'Tiefkühlgemüse',
    frozen_ice_cream: 'Eis und Desserts',
    frozen_fruit: 'Tiefkühlobst',
    frozen_meals: 'Tiefkühlgerichte',
    tinned_jarred: 'Konserven und Gläser',
    sauces: 'Soßen und Würzmittel',
    pantry: 'Vorräte',
    home_baking: 'Backzutaten',
    cooking_ingredients: 'Gewürze, Öl und internationale Küche',
    hot_drinks: 'Kaffee, Tee und Heißgetränke',
    drinks: 'Getränke',
    alcohol: 'Alkohol',
    pasta: 'Pasta',
    clothing: 'Bekleidung',
    household: 'Haushalt',
    health_beauty: 'Drogerie / Gesundheit und Schönheit',
    baby: 'Babybedarf',
    electrical: 'Elektroartikel',
    pet_supplies: 'Tierbedarf',
    seasonal: 'Saisonartikel',
  },
  keywords: {
    produce: ['apfel', 'banane', 'orange', 'erdbeeren', 'himbeeren', 'birne', 'trauben', 'zitrone', 'avocado', 'tomaten', 'kartoffeln', 'karotte', 'zwiebel', 'knoblauch', 'salat', 'gurke', 'paprika', 'zucchini', 'aubergine', 'champignons', 'spinat', 'brokkoli'],
    bakery_counter: ['brot', 'vollkornbrot', 'brötchen', 'brezel', 'croissant', 'kuchen', 'gebäck', 'toastbrot', 'laugenstange'],
    butcher_counter: ['fleisch', 'rindfleisch', 'schweinefleisch', 'hähnchen', 'pute', 'wurst', 'hackfleisch', 'schnitzel', 'bratwurst', 'speck'],
    fishmonger_counter: ['fisch', 'lachs', 'kabeljau', 'garnelen', 'forelle', 'hering', 'seelachs'],
    deli_counter: ['aufschnitt', 'schinken', 'salami', 'käseaufschnitt', 'leberwurst', 'fleischsalat', 'obazda'],
    chilled_milk_juice_cream: ['milch', 'butter', 'joghurt', 'quark', 'käse', 'frischkäse', 'sahne', 'eier', 'kefir', 'buttermilch'],
    cereal: ['müsli', 'cornflakes', 'haferflocken', 'knuspermüsli', 'porridge'],
    frozen_veg: ['tiefkühlgemüse', 'erbsen tiefgekühlt', 'spinat tiefgekühlt', 'pommes tiefgekühlt'],
    frozen_ice_cream: ['eis', 'speiseeis', 'eiscreme', 'wassereis'],
    frozen_fruit: ['tiefkühlobst', 'beeren tiefgekühlt', 'himbeeren tiefgekühlt'],
    frozen_meals: ['tiefkühlpizza', 'tiefkühlgericht', 'fertiggericht tiefgekühlt', 'lasagne tiefgekühlt'],
    tinned_jarred: ['konserve', 'dosentomaten', 'bohnen', 'kichererbsen', 'mais dose', 'gurken', 'apfelmus'],
    sauces: ['ketchup', 'tomatenketchup', 'mayonnaise', 'mayo', 'senf', 'grillsauce', 'barbecue sauce', 'sojasauce', 'sriracha', 'scharfe soße'],
    pantry: ['reis', 'linsen', 'brühe', 'salz', 'pfeffer', 'knödel', 'chips', 'salzstangen', 'cracker'],
    home_baking: ['mehl', 'zucker', 'puderzucker', 'backpulver', 'hefe', 'vanillezucker', 'schokotropfen'],
    cooking_ingredients: ['olivenöl', 'sonnenblumenöl', 'rapsöl', 'essig', 'balsamico', 'gewürze', 'paprikapulver'],
    hot_drinks: ['kaffee', 'kaffeepads', 'tee', 'kräutertee', 'kakao'],
    drinks: ['wasser', 'sprudelwasser', 'cola', 'apfelschorle', 'fanta', 'spezi'],
    alcohol: ['bier', 'pils', 'weizenbier', 'wein', 'sekt', 'riesling'],
    baby: ['windeln', 'feuchttücher', 'babynahrung', 'milchpulver'],
    household: ['waschmittel', 'spülmittel', 'toilettenpapier', 'küchenrolle', 'müllbeutel'],
    health_beauty: ['zahnpasta', 'shampoo', 'duschgel', 'deo'],
  },
});

export const IT_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'it',
  flag: '🇮🇹',
  label: 'Italy',
  groupLabels: {
    food_produce: 'Frutta e verdura',
    food_counters: 'Banchi freschi',
    food_chillers: 'Freschi',
    food_freezers: 'Surgelati',
    food_cupboard: 'Dispensa',
    non_food_general: 'Casa e cura personale',
  },
  sectionLabels: {
    produce: 'Frutta e verdura',
    bakery_counter: 'Pane e forno',
    butcher_counter: 'Macelleria',
    fishmonger_counter: 'Pescheria',
    deli_counter: 'Salumi e gastronomia',
    chilled_milk_juice_cream: 'Latte, formaggi e freschi',
    chilled_cooked_meat: 'Carni cotte confezionate',
    chilled_fresh_meat: 'Carne fresca confezionata',
    chilled_ready_meals: 'Piatti pronti freschi',
    baby_food: 'Alimenti per bambini',
    cereal: 'Cereali e colazione',
    snacks: 'Snack e patatine',
    frozen_veg: 'Verdure surgelate',
    frozen_ice_cream: 'Gelati',
    frozen_fruit: 'Frutta surgelata',
    frozen_meals: 'Piatti surgelati',
    tinned_jarred: 'Conserve e vasetti',
    sauces: 'Salse e condimenti',
    pantry: 'Scorte da dispensa',
    home_baking: 'Ingredienti per dolci',
    cooking_ingredients: 'Condimenti, spezie e cucina etnica',
    hot_drinks: 'Caffè, tè e bevande calde',
    drinks: 'Bevande',
    alcohol: 'Alcolici',
    clothing: 'Abbigliamento',
    household: 'Casa e pulizia',
    health_beauty: 'Farmacia / Salute e bellezza',
    baby: 'Prodotti per bambini',
    electrical: 'Elettronica',
    pet_supplies: 'Animali domestici',
    seasonal: 'Stagionale',
  },
  keywords: {
    produce: ['mela', 'banana', 'arancia', 'fragole', 'lamponi', 'pera', 'uva', 'limone', 'avocado', 'pomodoro', 'patate', 'carote', 'cipolla', 'aglio', 'insalata', 'cetriolo', 'peperoni', 'zucchine', 'melanzane', 'funghi', 'spinaci', 'broccoli'],
    bakery_counter: ['pane', 'pane integrale', 'focaccia', 'ciabatta', 'grissini', 'cornetto', 'brioche', 'taralli'],
    butcher_counter: ['macelleria', 'manzo', 'pollo', 'maiale', 'tacchino', 'salsiccia', 'carne macinata', 'prosciutto cotto', 'pancetta'],
    fishmonger_counter: ['pesce', 'salmone', 'merluzzo', 'tonno', 'gamberi', 'cozze', 'orata', 'branzino'],
    deli_counter: ['salumi', 'prosciutto', 'prosciutto crudo', 'salame', 'mortadella', 'bresaola', 'speck', 'gastronomia'],
    chilled_milk_juice_cream: ['latte', 'burro', 'yogurt', 'formaggio', 'mozzarella', 'parmigiano', 'pecorino', 'ricotta', 'uova', 'panna', 'mascarpone'],
    cereal: ['cereali', 'muesli', 'granola', 'fiocchi avena', 'fette biscottate'],
    frozen_veg: ['verdure surgelate', 'piselli surgelati', 'spinaci surgelati', 'patatine surgelate'],
    frozen_ice_cream: ['gelato', 'sorbetto', 'ghiaccioli', 'cornetti gelato'],
    frozen_fruit: ['frutti di bosco surgelati', 'fragole surgelate', 'mango surgelato'],
    frozen_meals: ['pizza surgelata', 'lasagne surgelate', 'piatti pronti surgelati', 'minestrone surgelato'],
    tinned_jarred: ['conserve', 'pomodori pelati', 'passata', 'ceci', 'fagioli', 'mais', 'tonno in scatola', 'olive', 'capperi'],
    sauces: ['ketchup', 'maionese', 'mayo', 'senape', 'salsa barbecue', 'salsa di soia', 'sriracha', 'salsa piccante', 'sugo pronto'],
    pantry: ['riso', 'polenta', 'lenticchie', 'brodo', 'sale', 'pepe', 'patatine', 'cracker', 'grissini confezionati'],
    home_baking: ['farina', 'zucchero', 'zucchero a velo', 'lievito', 'cacao', 'gocce di cioccolato', 'vanillina'],
    cooking_ingredients: ['olio extravergine', 'olio d oliva', 'olio di semi', 'aceto balsamico', 'origano', 'basilico', 'spezie'],
    hot_drinks: ['caffè', 'caffe', 'capsule caffè', 'tè', 'te', 'camomilla'],
    drinks: ['acqua', 'acqua frizzante', 'aranciata', 'chinotto', 'succo'],
    alcohol: ['vino rosso', 'vino bianco', 'prosecco', 'birra', 'aperol', 'limoncello'],
    pasta: ['spaghetti', 'penne', 'fusilli', 'rigatoni', 'tagliatelle', 'tortellini', 'gnocchi'],
    baby: ['pannolini', 'salviette', 'omogeneizzati', 'latte in polvere'],
    household: ['detersivo', 'detersivo piatti', 'carta igienica', 'carta cucina', 'sacchi spazzatura'],
    health_beauty: ['dentifricio', 'shampoo', 'bagnoschiuma', 'deodorante'],
  },
});

export const BE_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'be',
  flag: '🇧🇪',
  label: 'Belgium',
  groupLabels: {
    food_produce: 'Fruit & groenten / Fruits et légumes',
    food_counters: 'Versafdelingen / Rayons frais',
    food_chillers: 'Koeling / Frais',
    food_freezers: 'Diepvries / Surgelés',
    food_cupboard: 'Kruidenierswaren / Épicerie',
    non_food_general: 'Huishouden en verzorging / Maison et soins',
  },
  sectionLabels: {
    produce: 'Fruit & Groenten',
    bakery_counter: 'Bakkerij / Boulangerie',
    butcher_counter: 'Slagerij / Boucherie',
    fishmonger_counter: 'Vis / Poissonnerie',
    deli_counter: 'Charcuterie / Traiteur',
    chilled_milk_juice_cream: 'Zuivel / Crèmerie',
    chilled_cooked_meat: 'Gegaard vlees / Viande cuite',
    chilled_fresh_meat: 'Vers vlees verpakt / Viande fraîche',
    chilled_ready_meals: 'Verse maaltijden / Plats frais',
    baby_food: 'Babyvoeding / Alimentation bébé',
    cereal: 'Ontbijtgranen / Céréales',
    snacks: 'Snacks / Apéritifs',
    frozen_veg: 'Diepvriesgroenten / Légumes surgelés',
    frozen_ice_cream: 'IJs / Glaces',
    frozen_fruit: 'Diepvriesfruit / Fruits surgelés',
    frozen_meals: 'Diepvriesmaaltijden / Plats surgelés',
    tinned_jarred: 'Conserven / Conserves',
    sauces: 'Sauzen / Sauces',
    pantry: 'Voorraadkast / Épicerie',
    home_baking: 'Bakken / Pâtisserie',
    cooking_ingredients: 'Kruiden, olie en wereldkeuken',
    hot_drinks: 'Koffie, thee en warme dranken',
    drinks: 'Dranken / Boissons',
    alcohol: 'Alcohol / Alcool',
    pasta: 'Pasta / Pâtes',
    clothing: 'Kleding / Vêtements',
    household: 'Huishouden / Maison',
    health_beauty: 'Drogisterij / Hygiène et beauté',
    baby: 'Baby / Bébé',
    electrical: 'Elektrisch / Électricité',
    pet_supplies: 'Dieren / Animaux',
    seasonal: 'Seizoen / Saisonnier',
  },
  keywords: {
    produce: ['appel', 'pomme', 'banaan', 'banane', 'sinaasappel', 'orange', 'fraise', 'aardbei', 'framboos', 'framboise', 'tomaat', 'tomate', 'aardappel', 'pomme de terre', 'wortel', 'carotte', 'ui', 'oignon', 'sla', 'salade', 'komkommer', 'concombre', 'paprika', 'champignon', 'prei', 'poireau'],
    bakery_counter: ['brood', 'pain', 'stokbrood', 'baguette', 'croissant', 'pistolet', 'koffiekoek', 'sandwich', 'suikerbrood'],
    butcher_counter: ['slagerij', 'boucherie', 'rundvlees', 'boeuf', 'kip', 'poulet', 'varkensvlees', 'porc', 'gehakt', 'haché', 'chipolata'],
    fishmonger_counter: ['vis', 'poisson', 'zalm', 'saumon', 'kabeljauw', 'cabillaud', 'garnalen', 'crevettes', 'mosselen', 'moules'],
    deli_counter: ['charcuterie', 'ham', 'jambon', 'salami', 'prepare', 'préparé', 'filet americain', 'americain préparé'],
    chilled_milk_juice_cream: ['melk', 'lait', 'boter', 'beurre', 'yoghurt', 'yaourt', 'kaas', 'fromage', 'eieren', 'oeufs', 'room', 'crème'],
    cereal: ['cornflakes', 'muesli', 'granola', 'havermout', 'flocons avoine', 'ontbijtgranen'],
    frozen_veg: ['diepvriesgroenten', 'légumes surgelés', 'diepvrieserwten', 'petits pois surgelés', 'diepvriesfrieten'],
    frozen_ice_cream: ['ijs', 'glace', 'roomijs', 'sorbet', 'waterijs'],
    frozen_fruit: ['diepvriesfruit', 'fruits surgelés', 'frambozen diepvries', 'framboises surgelées'],
    frozen_meals: ['diepvriespizza', 'pizza surgelée', 'diepvriesmaaltijd', 'plats surgelés', 'vol au vent diepvries'],
    tinned_jarred: ['conserven', 'conserve', 'bonen', 'haricots', 'kikkererwten', 'pois chiches', 'tomatenblokjes', 'tomates concassées', 'appelmoes'],
    sauces: ['mayonaise', 'mayonnaise', 'ketchup', 'mosterd', 'moutarde', 'andalouse', 'samurai saus', 'sauce samouraï', 'barbecuesaus', 'sauce barbecue', 'sojasaus', 'sauce soja'],
    pantry: ['rijst', 'riz', 'linzen', 'lentilles', 'bouillon', 'zout', 'sel', 'peper', 'poivre', 'chips', 'speculoos'],
    home_baking: ['bloem', 'farine', 'suiker', 'sucre', 'bloemsuiker', 'sucre glace', 'bakpoeder', 'levure chimique', 'gist', 'levure'],
    cooking_ingredients: ['olijfolie', 'huile olive', 'zonnebloemolie', 'azijn', 'vinaigre', 'balsamico', 'specerijen', 'épices'],
    hot_drinks: ['koffie', 'café', 'thee', 'thé', 'chocolademelk', 'chocolat chaud'],
    drinks: ['water', 'eau', 'spuitwater', 'eau pétillante', 'cola', 'limonade'],
    alcohol: ['bier', 'bière', 'trappist', 'tripel', 'wijn', 'vin', 'cava'],
    baby: ['luiers', 'couches', 'babydoekjes', 'lingettes bébé', 'babyvoeding'],
    household: ['wasmiddel', 'lessive', 'afwasmiddel', 'liquide vaisselle', 'toiletpapier', 'papier toilette'],
    health_beauty: ['tandpasta', 'dentifrice', 'shampoo', 'gel douche', 'deodorant'],
  },
});

export const ES_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'es',
  flag: '🇪🇸',
  label: 'Spain',
  groupLabels: {
    food_produce: 'Fruta y verdura',
    food_counters: 'Mostradores frescos',
    food_chillers: 'Refrigerados',
    food_freezers: 'Congelados',
    food_cupboard: 'Despensa',
    non_food_general: 'Hogar y cuidado personal',
  },
  sectionLabels: {
    produce: 'Fruta y verdura',
    bakery_counter: 'Panadería',
    butcher_counter: 'Carnicería',
    fishmonger_counter: 'Pescadería',
    deli_counter: 'Charcutería',
    chilled_milk_juice_cream: 'Lácteos y refrigerados',
    chilled_cooked_meat: 'Carne cocida envasada',
    chilled_fresh_meat: 'Carne fresca envasada',
    chilled_ready_meals: 'Platos preparados refrigerados',
    baby_food: 'Alimentación infantil',
    cereal: 'Cereales y desayuno',
    snacks: 'Aperitivos y patatas',
    frozen_veg: 'Verduras congeladas',
    frozen_ice_cream: 'Helados',
    frozen_fruit: 'Fruta congelada',
    frozen_meals: 'Platos congelados',
    tinned_jarred: 'Conservas y frascos',
    sauces: 'Salsas y condimentos',
    pantry: 'Básicos de despensa',
    home_baking: 'Repostería',
    cooking_ingredients: 'Aceites, especias y cocina internacional',
    hot_drinks: 'Café, té y bebidas calientes',
    drinks: 'Bebidas',
    alcohol: 'Alcohol',
    pasta: 'Pasta',
    clothing: 'Ropa',
    household: 'Hogar y limpieza',
    health_beauty: 'Farmacia / Salud y belleza',
    baby: 'Bebé',
    electrical: 'Electricidad',
    pet_supplies: 'Mascotas',
    seasonal: 'Temporada',
  },
  keywords: {
    produce: ['manzana', 'plátano', 'platano', 'naranja', 'fresas', 'frambuesas', 'pera', 'uva', 'limón', 'aguacate', 'tomate', 'patata', 'zanahoria', 'cebolla', 'ajo', 'lechuga', 'pepino', 'pimiento', 'calabacín', 'berenjena', 'champiñones', 'espinacas'],
    bakery_counter: ['pan', 'barra de pan', 'baguette', 'croissant', 'bollería', 'magdalenas', 'ensaimada', 'pan integral'],
    butcher_counter: ['carnicería', 'carne', 'ternera', 'pollo', 'cerdo', 'cordero', 'pavo', 'carne picada', 'chorizo', 'longaniza'],
    fishmonger_counter: ['pescado', 'salmón', 'merluza', 'bacalao', 'atún', 'gambas', 'mejillones', 'dorada', 'lubina'],
    deli_counter: ['charcutería', 'jamón', 'jamón serrano', 'jamón ibérico', 'jamón cocido', 'salchichón', 'lomo', 'queso manchego'],
    chilled_milk_juice_cream: ['leche', 'mantequilla', 'yogur', 'queso', 'manchego', 'nata', 'huevos', 'zumo', 'cuajada'],
    cereal: ['cereales', 'muesli', 'granola', 'copos de avena', 'galletas desayuno'],
    frozen_veg: ['verduras congeladas', 'guisantes congelados', 'espinacas congeladas', 'patatas fritas congeladas'],
    frozen_ice_cream: ['helado', 'sorbete', 'polos', 'cucuruchos helado'],
    frozen_fruit: ['fruta congelada', 'frutos rojos congelados', 'mango congelado'],
    frozen_meals: ['pizza congelada', 'croquetas congeladas', 'lasaña congelada', 'platos preparados congelados'],
    tinned_jarred: ['conservas', 'tomate triturado', 'garbanzos', 'alubias', 'maíz dulce', 'aceitunas', 'atún en lata', 'pimientos piquillo'],
    sauces: ['ketchup', 'mayonesa', 'mayo', 'mostaza', 'salsa barbacoa', 'salsa soja', 'sriracha', 'salsa picante', 'tomate frito'],
    pantry: ['arroz', 'lentejas', 'caldo', 'sal', 'pimienta', 'patatas fritas', 'picos', 'regañás'],
    home_baking: ['harina', 'azúcar', 'azucar', 'azúcar glas', 'levadura', 'cacao', 'pepitas chocolate'],
    cooking_ingredients: ['aceite de oliva', 'aceite girasol', 'aceite', 'vinagre', 'vinagre balsámico', 'pimentón', 'azafrán', 'comino'],
    hot_drinks: ['café', 'capsulas café', 'té', 'infusión', 'chocolate caliente'],
    drinks: ['agua', 'agua con gas', 'refresco', 'cola', 'fanta', 'zumo'],
    alcohol: ['vino tinto', 'vino blanco', 'cava', 'cerveza', 'sidra', 'sangría'],
    baby: ['pañales', 'toallitas bebé', 'potitos', 'leche infantil'],
    household: ['detergente', 'lavavajillas', 'papel higiénico', 'papel cocina', 'bolsas basura'],
    health_beauty: ['pasta de dientes', 'champú', 'gel de ducha', 'desodorante'],
  },
});

export const RO_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'ro',
  flag: '🇷🇴',
  label: 'Romania',
  groupLabels: {
    food_produce: 'Fructe și legume',
    food_counters: 'Raioane proaspete',
    food_chillers: 'Proaspete și refrigerate',
    food_freezers: 'Congelate',
    food_cupboard: 'Cămara',
    non_food_general: 'Casă și îngrijire personală',
  },
  sectionLabels: {
    produce: 'Fructe și legume',
    bakery_counter: 'Brutărie',
    butcher_counter: 'Măcelărie',
    fishmonger_counter: 'Pește',
    deli_counter: 'Mezeluri / Delicatese',
    chilled_milk_juice_cream: 'Lactate și refrigerate',
    chilled_cooked_meat: 'Carne gătită ambalată',
    chilled_fresh_meat: 'Carne proaspătă ambalată',
    chilled_ready_meals: 'Mâncare gata preparată refrigerată',
    baby_food: 'Mâncare pentru bebeluși',
    cereal: 'Cereale și mic dejun',
    snacks: 'Gustări și chipsuri',
    frozen_veg: 'Legume congelate',
    frozen_ice_cream: 'Înghețată',
    frozen_fruit: 'Fructe congelate',
    frozen_meals: 'Mâncare congelată',
    tinned_jarred: 'Conserve și borcane',
    sauces: 'Sosuri și condimente',
    pantry: 'Produse de cămară',
    home_baking: 'Ingrediente pentru prăjituri',
    cooking_ingredients: 'Condimente, uleiuri și ingrediente',
    hot_drinks: 'Cafea, ceai și băuturi calde',
    drinks: 'Băuturi',
    alcohol: 'Alcool',
    pasta: 'Paste',
    clothing: 'Îmbrăcăminte',
    household: 'Casă și curățenie',
    health_beauty: 'Farmacie / Sănătate și frumusețe',
    baby: 'Bebeluși',
    electrical: 'Electrice',
    pet_supplies: 'Animale de companie',
    seasonal: 'Sezonier',
  },
  keywords: {
    produce: ['măr', 'mar', 'banană', 'banana', 'portocală', 'portocala', 'capsuni', 'căpșuni', 'zmeură', 'zmeura', 'pară', 'pere', 'struguri', 'lămâie', 'lamaie', 'avocado', 'roșii', 'rosii', 'cartofi', 'morcovi', 'ceapă', 'ceapa', 'usturoi', 'salată', 'salata', 'castravete', 'ardei', 'dovlecei', 'vinete', 'ciuperci', 'spanac'],
    bakery_counter: ['pâine', 'paine', 'pâine integrală', 'paine integrala', 'chifle', 'covrigi', 'cozonac', 'cornuri', 'lipie'],
    butcher_counter: ['carne', 'vită', 'vita', 'pui', 'porc', 'curcan', 'miel', 'carne tocată', 'carne tocata', 'carnati', 'cârnați', 'slănină', 'slanina'],
    fishmonger_counter: ['pește', 'peste', 'somon', 'cod', 'ton', 'creveți', 'creveti', 'păstrăv', 'pastrav'],
    deli_counter: ['mezeluri', 'șuncă', 'sunca', 'salam', 'parizer', 'cașcaval', 'cascaval', 'telemea'],
    chilled_milk_juice_cream: ['lapte', 'unt', 'iaurt', 'brânză', 'branza', 'smântână', 'smantana', 'ouă', 'oua', 'chefir'],
    cereal: ['cereale', 'musli', 'granola', 'fulgi de ovăz', 'fulgi de ovaz'],
    frozen_veg: ['legume congelate', 'mazăre congelată', 'mazare congelata', 'spanac congelat', 'cartofi congelați', 'cartofi congelati'],
    frozen_ice_cream: ['înghețată', 'inghetata', 'sorbet', 'înghețată pe băț', 'inghetata pe bat'],
    frozen_fruit: ['fructe congelate', 'fructe de pădure congelate', 'fructe de padure congelate', 'zmeură congelată', 'zmeura congelata'],
    frozen_meals: ['pizza congelată', 'pizza congelata', 'mâncare congelată', 'mancare congelata', 'semipreparate congelate'],
    tinned_jarred: ['conserve', 'fasole', 'năut', 'naut', 'roșii la conservă', 'rosii la conserva', 'porumb conservă', 'porumb conserva', 'murături', 'muraturi', 'zacuscă', 'zacusca'],
    sauces: ['ketchup', 'maioneză', 'maioneza', 'muștar', 'mustar', 'sos barbecue', 'sos barbeque', 'sos de soia', 'sriracha', 'sos picant', 'sos de roșii', 'sos de rosii'],
    pantry: ['orez', 'linte', 'mălai', 'malai', 'sare', 'piper', 'cuburi supă', 'cuburi supa', 'chipsuri', 'biscuiți sărați', 'biscuiti sarati'],
    home_baking: ['făină', 'faina', 'zahăr', 'zahar', 'zahăr pudră', 'zahar pudra', 'praf de copt', 'drojdie', 'cacao'],
    cooking_ingredients: ['ulei', 'ulei de măsline', 'ulei de masline', 'otet', 'oțet', 'boia', 'condimente'],
    hot_drinks: ['cafea', 'ceai', 'ceai verde', 'ciocolată caldă', 'ciocolata calda'],
    drinks: ['apă', 'apa', 'apă minerală', 'apa minerala', 'suc', 'cola'],
    alcohol: ['bere', 'vin roșu', 'vin rosu', 'vin alb', 'țuică', 'tuica', 'palincă', 'palinca'],
    baby: ['scutece', 'șervețele umede', 'servetele umede', 'mâncare bebeluși', 'mancare bebelusi', 'lapte praf'],
    household: ['detergent', 'detergent vase', 'hârtie igienică', 'hartie igienica', 'prosoape hârtie', 'saci menajeri'],
    health_beauty: ['pastă de dinți', 'pasta de dinti', 'șampon', 'sampon', 'gel de duș', 'gel de dus', 'deodorant'],
  },
});

export const MX_CONFIG = createInternationalConfig({
  base: US_CONFIG,
  code: 'mx',
  flag: '🇲🇽',
  label: 'Mexico',
  groupLabels: MEXICO_GROUP_LABELS,
  sectionLabels: {
    produce: 'Frutas y verduras',
    bakery_counter: 'Panadería',
    butcher_counter: 'Carnicería',
    seafood_counter: 'Pescadería',
    deli_counter: 'Salchichonería / Comida preparada',
    chilled_milk_juice_cream: 'Lácteos y refrigerados',
    chilled_cooked_meat: 'Carnes frías empacadas',
    chilled_fresh_meat: 'Carne fresca empacada',
    chilled_ready_meals: 'Comidas preparadas refrigeradas',
    cereal: 'Cereales y desayuno',
    frozen_veg: 'Verduras congeladas',
    frozen_ice_cream: 'Helados y paletas',
    frozen_fruit: 'Fruta congelada',
    frozen_meals: 'Comidas congeladas',
    tinned_jarred: 'Enlatados y abarrotes',
    pantry: 'Básicos de despensa',
    cooking_ingredients: 'Aceites, especias y cocina mexicana',
    hot_drinks: 'Café, té y bebidas calientes',
    alcohol: 'Alcohol',
    pasta: 'Pasta',
    snacks: 'Botanas y dulces',
    drinks: 'Bebidas',
    baby_food: 'Bebé y fórmula',
    baby: 'Pañales y bebé',
    clothing: 'Ropa',
    household: 'Hogar y limpieza',
    health_beauty: 'Farmacia / Cuidado personal',
    electrical: 'Electrónicos',
    pet_supplies: 'Mascotas',
    seasonal: 'Temporada',
  },
  keywords: {
    produce: ['manzana', 'plátano', 'platano', 'naranja', 'limón', 'limon', 'aguacate', 'jitomate', 'tomate verde', 'tomate', 'papa', 'zanahoria', 'cebolla', 'ajo', 'chile', 'jalapeño', 'jalapeno', 'serrano', 'poblano', 'cilantro', 'nopales', 'elote', 'calabacita', 'chayote'],
    bakery_counter: ['pan dulce', 'bolillo', 'telera', 'concha', 'tortillas', 'tortilla de maiz', 'tortillas de maíz', 'pan de caja', 'birote', 'cemita'],
    butcher_counter: ['carnicería', 'carne', 'res', 'pollo', 'cerdo', 'arrachera', 'suadero', 'pastor', 'carne molida', 'chorizo', 'longaniza'],
    seafood_counter: ['pescado', 'salmón', 'atun', 'atún', 'camarón', 'camaron', 'tilapia', 'mojarra', 'pulpo'],
    deli_counter: ['jamón', 'jamon', 'salchicha', 'salchichas', 'queso Oaxaca', 'quesillo', 'queso manchego', 'queso panela', 'pollo rostizado'],
    chilled_milk_juice_cream: ['leche', 'mantequilla', 'yogur', 'queso', 'queso fresco', 'crema', 'huevos', 'jocoque', 'media crema'],
    frozen_veg: ['verduras congeladas', 'elote congelado', 'chícharos congelados', 'chicharos congelados'],
    frozen_ice_cream: ['helado', 'paletas', 'nieve', 'bolis'],
    frozen_fruit: ['fruta congelada', 'mango congelado', 'fresas congeladas'],
    frozen_meals: ['pizza congelada', 'taquitos congelados', 'comida congelada'],
    tinned_jarred: ['frijoles', 'frijoles negros', 'frijoles refritos', 'maíz en lata', 'maiz en lata', 'chiles enlatados', 'rajas en lata', 'champiñones en lata'],
    pantry: ['arroz', 'lentejas', 'caldo', 'sal', 'pimienta', 'totopos', 'galletas saladas', 'tostadas'],
    home_baking: ['harina', 'azúcar', 'azucar', 'levadura', 'harina de maiz', 'harina de maíz', 'masa harina', 'piloncillo'],
    cooking_ingredients: ['aceite', 'aceite de oliva', 'vinagre', 'comino', 'orégano', 'oregano', 'achiote', 'mole', 'salsa soja', 'salsa de soya', 'salsa verde', 'salsa roja', 'salsa taquera', 'salsa macha', 'valentina', 'chamoy', 'mayonesa', 'catsup', 'ketchup', 'mostaza'],
    hot_drinks: ['café', 'cafe', 'chocolate abuelita', 'té', 'te'],
    drinks: ['agua', 'agua mineral', 'refresco', 'coca cola', 'jarritos', 'boing', 'jumex'],
    alcohol: ['cerveza', 'tequila', 'mezcal', 'vino tinto', 'vino blanco'],
    baby_food: ['fórmula bebé', 'formula bebe', 'papilla', 'gerber'],
    baby: ['pañales', 'panales', 'toallitas húmedas', 'toallitas humedas'],
    household: ['detergente', 'jabón para trastes', 'jabon para trastes', 'papel higiénico', 'papel higienico', 'servitoallas', 'bolsas de basura'],
    health_beauty: ['pasta dental', 'shampoo', 'jabón corporal', 'jabon corporal', 'desodorante'],
  },
});

export const NL_CONFIG = createInternationalConfig({
  base: UK_CONFIG,
  code: 'nl',
  flag: '🇳🇱',
  label: 'Netherlands',
  groupLabels: {
    food_produce: 'Groente en fruit',
    food_counters: 'Versafdelingen',
    food_chillers: 'Koeling',
    food_freezers: 'Diepvries',
    food_cupboard: 'Kruidenierswaren',
    non_food_general: 'Huishouden en persoonlijke verzorging',
  },
  sectionLabels: {
    produce: 'Groente en fruit',
    bakery_counter: 'Bakkerij',
    butcher_counter: 'Slagerij',
    fishmonger_counter: 'Vis',
    deli_counter: 'Vleeswaren / Delicatessen',
    chilled_milk_juice_cream: 'Zuivel en koeling',
    chilled_cooked_meat: 'Gegaard vlees, verpakt',
    chilled_fresh_meat: 'Vers vlees, verpakt',
    chilled_ready_meals: 'Verse kant-en-klaarmaaltijden',
    baby_food: 'Babyvoeding',
    cereal: 'Ontbijtgranen',
    snacks: 'Snacks en chips',
    frozen_veg: 'Diepvriesgroenten',
    frozen_ice_cream: 'IJs',
    frozen_fruit: 'Diepvriesfruit',
    frozen_meals: 'Diepvriesmaaltijden',
    tinned_jarred: 'Conserven en potten',
    sauces: 'Sauzen en smaakmakers',
    pantry: 'Voorraadkast',
    home_baking: 'Bakken',
    cooking_ingredients: 'Kruiden, olie en wereldkeuken',
    hot_drinks: 'Koffie, thee en warme dranken',
    drinks: 'Dranken',
    alcohol: 'Alcohol',
    pasta: 'Pasta',
    clothing: 'Kleding',
    household: 'Huishouden',
    health_beauty: 'Drogisterij / Gezondheid en verzorging',
    baby: 'Babybenodigdheden',
    electrical: 'Elektrische artikelen',
    pet_supplies: 'Dierenbenodigdheden',
    seasonal: 'Seizoensartikelen',
  },
  keywords: {
    produce: ['appel', 'banaan', 'sinaasappel', 'aardbei', 'framboos', 'peer', 'druiven', 'citroen', 'avocado', 'tomaat', 'aardappel', 'wortel', 'ui', 'knoflook', 'sla', 'komkommer', 'paprika', 'courgette', 'aubergine', 'champignon', 'spinazie', 'broccoli'],
    bakery_counter: ['brood', 'volkorenbrood', 'bolletjes', 'croissant', 'stokbrood', 'krentenbol', 'beschuit', 'eierkoek'],
    butcher_counter: ['slagerij', 'rundvlees', 'kip', 'varkensvlees', 'kalkoen', 'gehakt', 'worst', 'spek', 'rookworst'],
    fishmonger_counter: ['vis', 'zalm', 'kabeljauw', 'garnalen', 'haring', 'makreel', 'kibbeling'],
    deli_counter: ['vleeswaren', 'ham', 'salami', 'kaas plakjes', 'filet americain', 'leverworst', 'ei salade'],
    chilled_milk_juice_cream: ['melk', 'boter', 'yoghurt', 'kwark', 'kaas', 'gouda', 'slagroom', 'eieren', 'karnemelk', 'vla'],
    cereal: ['ontbijtgranen', 'muesli', 'cruesli', 'havermout', 'cornflakes'],
    frozen_veg: ['diepvriesgroenten', 'diepvrieserwten', 'diepvriesspinazie', 'diepvriesfriet'],
    frozen_ice_cream: ['ijs', 'roomijs', 'waterijs', 'sorbetijs'],
    frozen_fruit: ['diepvriesfruit', 'diepvries aardbeien', 'diepvries mango', 'bevroren fruit'],
    frozen_meals: ['diepvriespizza', 'diepvriesmaaltijd', 'lasagne diepvries', 'diepvries snacks'],
    tinned_jarred: ['conserven', 'bonen', 'kikkererwten', 'tomatenblokjes', 'mais blik', 'augurken', 'appelmoes', 'pindakaas'],
    sauces: ['mayonaise', 'mayo', 'ketchup', 'tomatenketchup', 'mosterd', 'barbecuesaus', 'sojasaus', 'sriracha', 'sambal', 'chilisaus'],
    pantry: ['rijst', 'linzen', 'bouillon', 'zout', 'peper', 'hagelslag', 'chips', 'borrelnootjes', 'crackers'],
    home_baking: ['bloem', 'suiker', 'poedersuiker', 'bakpoeder', 'gist', 'vanillesuiker', 'cacaopoeder'],
    cooking_ingredients: ['olijfolie', 'zonnebloemolie', 'azijn', 'balsamico', 'kruiden', 'paprikapoeder', 'ketjap'],
    hot_drinks: ['koffie', 'koffiepads', 'thee', 'muntthee', 'chocolademelk'],
    drinks: ['water', 'spa rood', 'frisdrank', 'cola', 'sinas', 'sap'],
    alcohol: ['bier', 'pils', 'wijn', 'jenever', 'prosecco'],
    baby: ['luiers', 'babydoekjes', 'babyvoeding', 'flesvoeding'],
    household: ['wasmiddel', 'afwasmiddel', 'toiletpapier', 'keukenrol', 'vuilniszakken'],
    health_beauty: ['tandpasta', 'shampoo', 'douchegel', 'deodorant'],
  },
});
