import type { CountryConfig } from '../../types';

export const UK_CONFIG: CountryConfig = {
  code: 'uk',
  flag: '🇬🇧',
  label: 'United Kingdom',
  groups: [
    {
      key: 'food_produce',
      label: 'Produce (Fruit & Veg)',
      order: 1,
      sections: [
        {
          key: 'produce',
          label: 'Produce',
          keywords: [
            'apple', 'banana', 'orange', 'grape', 'berries', 'strawberry', 'blueberry', 'raspberry', 'blackberry',
            'melon', 'pineapple', 'pear', 'peach', 'plum', 'kiwi', 'mango', 'lemon', 'lime', 'avocado', 'tomato', 'tomatoes',
            'potato', 'sweet potato', 'carrot', 'onion', 'red onion', 'spring onion', 'garlic', 'pepper', 'chilli',
            'broccoli', 'cauliflower', 'cucumber', 'lettuce', 'salad', 'spinach', 'kale', 'cabbage', 'mushroom',
            'courgette', 'aubergine', 'celery', 'leek', 'ginger', 'herbs', 'coriander', 'parsley', 'basil',
            'chopped veg', 'prepared veg', 'stir fry veg', 'stir-fry veg', 'stir fry mix', 'stir-fry mix',
            'bagged salad', 'bagged salads', 'coleslaw', 'rocket', 'watercress',
          ],
        },
      ],
    },
    {
      key: 'food_counters',
      label: 'In-store Counters',
      order: 2,
      sections: [
        {
          key: 'bakery_counter',
          label: 'Bakery',
          keywords: [
            'fresh bread', 'bread', 'roll', 'bagel', 'bun', 'croissant', 'wrap', 'tortilla', 'pitta', 'naan', 'cake',
            'muffin', 'crumpet', 'teacake', 'scone', 'brioche', 'baguette', 'pastry', 'donut', 'doughnut', 'hot cross bun',
          ],
        },
        {
          key: 'butcher_counter',
          label: 'Butcher / Meat Counter',
          keywords: [
            'butcher', 'beef joint', 'beef steak', 'steak', 'roasting joint', 'pork chop', 'pork chops',
            'lamb shank', 'lamb leg', 'lamb chops', 'whole chicken', 'marinated chicken', 'marinated meat',
            'ready to cook meat', 'ready-to-cook meat',
          ],
        },
        {
          key: 'fishmonger_counter',
          label: 'Fishmonger',
          keywords: [
            'fishmonger', 'fresh fish', 'salmon', 'salmon fillet', 'fresh salmon fillet', 'cod', 'cod fillet',
            'fresh cod fillet', 'haddock', 'haddock fillet', 'sea bass', 'sea bass fillet', 'whole fish',
            'prawns', 'shellfish', 'smoked salmon', 'smoked mackerel', 'breaded fish', 'ready to cook fish',
            'ready-to-cook fish',
          ],
        },
        {
          key: 'deli_counter',
          label: 'Deli / Delicatessen',
          keywords: [
            'deli', 'cold meats', 'sliced ham', 'pastrami', 'continental meats', 'deli cheese', 'rotisserie chicken', 'hot chicken',
          ],
        },
      ],
    },
    {
      key: 'food_chillers',
      label: 'Chillers',
      order: 3,
      sections: [
        {
          key: 'chilled_milk_juice_cream',
          label: 'Milk / Juice / Cream',
          keywords: [
            'milk', 'whole milk', 'semi skimmed milk', 'semi-skimmed milk', 'skimmed milk', 'oat milk', 'almond milk',
            'gold milk',
            'blue milk', 'green milk', 'red milk',
            'juice', 'orange juice', 'apple juice', 'mango juice', 'smoothie', 'cream', 'single cream', 'double cream',
            'whipped cream', 'whipping cream', 'butter', 'yogurt', 'yoghurt', 'cheese', 'cheddar', 'mozzarella',
            'parmesan', 'halloumi', 'egg', 'eggs', 'creme fraiche', 'crème fraîche', 'custard', 'cottage cheese',
            'soft cheese', 'sour cream', 'buttermilk', 'kefir',
          ],
        },
        {
          key: 'chilled_cooked_meat',
          label: 'Cooked Meat, Prepackaged',
          keywords: [
            'cooked ham', 'ham slices', 'wafer thin ham', 'turkey slices', 'roast beef slices', 'chicken slices', 'salami pack', 'pepperoni slices',
          ],
        },
        {
          key: 'chilled_fresh_meat',
          label: 'Fresh Meat, Prepackaged',
          keywords: [
            'minced beef', 'beef mince', 'mince', 'beef steaks', 'beef roasting joint', 'sausages', 'pork sausages',
            'burgers', 'uncooked chicken', 'chicken thighs', 'chicken breast', 'chicken breasts', 'bacon', 'pork loin',
            'pork chops', 'lamb chops', 'lamb leg', 'marinated chicken', 'marinated pork',
          ],
        },
        {
          key: 'chilled_ready_meals',
          label: 'Ready Meals',
          keywords: [
            'ready meal', 'ready meals', 'lasagna', 'lasagne', 'chilled pizza', 'fresh pizza', 'microwave meal',
            'pasta bake', 'meal for one', 'sandwich', 'sandwiches', 'wrap meal deal', 'meal deal', 'pasta salad',
            'chilled pasta salad', 'coleslaw side', 'prepared salad',
          ],
        },
      ],
    },
    {
      key: 'food_freezers',
      label: 'Freezers',
      order: 4,
      sections: [
        {
          key: 'frozen_veg',
          label: 'Frozen Veg',
          keywords: ['frozen veg', 'frozen vegetables', 'frozen peas', 'frozen sweetcorn', 'frozen broccoli', 'frozen spinach', 'frozen green beans', 'frozen mixed veg', 'frozen mixed vegetables', 'frozen carrots', 'frozen cauliflower', 'frozen edamame', 'frozen mushrooms', 'frozen peppers', 'frozen onions'],
        },
        {
          key: 'frozen_ice_cream',
          label: 'Ice Cream',
          keywords: ['ice cream', 'icecream', 'ice-cream', 'gelato', 'sorbet', 'frozen yogurt', 'frozen yoghurt', 'frozen dessert', 'ice lolly', 'ice lollies', 'lolly', 'lollies', 'popsicle', 'ice pop', 'ice pops', 'ice cream cones', 'ice cream sandwich', 'ice cream sandwiches', 'magnum', 'cornetto', 'twister lolly', 'solero', 'fab lolly', 'calippo', 'ben and jerrys', 'ben and jerry\'s', 'haagen dazs', 'häagen-dazs'],
        },
        {
          key: 'frozen_fruit',
          label: 'Frozen Fruit',
          keywords: ['frozen fruit', 'frozen berries', 'frozen mixed berries', 'summer fruits', 'frozen summer fruits', 'frozen mango', 'frozen pineapple', 'frozen strawberries', 'frozen blueberries', 'frozen raspberries', 'frozen blackberries', 'frozen cherries', 'frozen peaches', 'frozen banana', 'smoothie mix', 'smoothie fruit'],
        },
        {
          key: 'frozen_meals',
          label: 'Frozen Meals',
          keywords: ['frozen pizza', 'frozen meal', 'frozen meals', 'frozen lasagna', 'frozen lasagne', 'frozen chips', 'chips', 'frozen fries', 'waffles', 'potato waffles', 'hash brown', 'hash browns', 'fish fingers', 'chicken nuggets', 'frozen chicken nuggets', 'chicken dippers', 'frozen burgers', 'frozen sausages', 'frozen garlic bread', 'garlic bread', 'frozen Yorkshire puddings', 'yorkshire puddings', 'frozen roast potatoes', 'roast potatoes', 'frozen onion rings', 'onion rings', 'frozen pies', 'frozen pie', 'frozen pastry', 'frozen prawns', 'frozen fish'],
        },
      ],
    },
    {
      key: 'food_cupboard',
      label: 'Cupboard Staples',
      order: 5,
      sections: [
        {
          key: 'baby_food',
          label: 'Baby Food',
          keywords: [
            'baby food',
            'baby rice',
            'weaning',
            'weaning food',
            'puree',
            'purees',
            'jar food',
            'baby jars',
            'baby porridge',
            'baby cereal',
            'snacks for babies',
            'finger food',
          ],
        },
        {
          key: 'cereal',
          label: 'Cereal Aisle',
          keywords: [
            'cereal',
            'breakfast cereal',
            'corn flakes',
            'cornflakes',
            'frosties',
            'frosted flakes',
            'weetabix',
            'weetos',
            'cheerios',
            'shreddies',
            'shredded wheat',
            'rice krispies',
            'coco pops',
            'crunch clusters',
            'granola',
            'muesli',
            'porridge',
            'porridge oats',
            'oats',
            'ready brek',
            'bran flakes',
            'special k',
            'krave',
            'wheat biscuits',
            'honey hoops',
          ],
        },
        {
          key: 'snacks',
          label: 'Snacks & Crisps',
          keywords: [
            'crisps',
            'crisp multipack',
            'multipack crisps',
            'walkers crisps',
            'doritos',
            'pringles',
            'popchips',
            'snack',
            'snacks',
            'chocolate',
            'chocolate bar',
            'chocolate bars',
            'cadbury',
            'galaxy',
            'kit kat',
            'kitkat',
            'mars bar',
            'snickers',
            'twix',
            'biscuit',
            'biscuits',
            'digestives',
            'rich tea',
            'cookies',
            'nuts',
            'peanuts',
            'cashews',
            'popcorn',
            'sweet',
            'sweets',
            'haribo',
            'wine gums',
            'fruit pastilles',
          ],
        },
        {
          key: 'tinned_jarred',
          label: 'Tinned & Jarred Goods',
          keywords: [
            'tinned',
            'tinned food',
            'tinned vegetables',
            'tinned peas',
            'tinned sweetcorn',
            'tinned carrots',
            'tinned beans',
            'baked beans',
            'kidney beans',
            'black beans',
            'butter beans',
            'chickpeas',
            'tinned chickpeas',
            'lentils',
            'tinned lentils',
            'soup',
            'tinned soup',
            'tinned tomatoes',
            'chopped tomatoes',
            'plum tomatoes',
            'passata',
            'jarred sauce',
            'jar sauce',
            'pasta sauce',
            'curry sauce',
            'curry jar',
            'pesto',
            'pickles',
            'pickle',
            'olives',
          ],
        },
        {
          key: 'pantry',
          label: 'Pantry Staples',
          keywords: [
            'pantry',
            'rice',
            'basmati rice',
            'jasmine rice',
            'brown rice',
            'white rice',
            'wild rice',
            'arborio rice',
            'long grain rice',
            'microwave rice',
            'quinoa',
            'couscous',
            'stock',
            'jam',
            'honey',
            'salt',
            'pepper',
            'peanut butter',
            'marmalade',
            'gravy granules',
            'stock cubes',
          ],
        },
        {
          key: 'cooking_ingredients',
          label: 'Cooking Ingredients & World Foods',
          keywords: [
            'cooking ingredients',
            'herbs and spices',
            'spices',
            'mixed herbs',
            'oregano',
            'paprika',
            'cumin',
            'turmeric',
            'cinnamon',
            'seasoning',
            'cooking oil',
            'oil',
            'olive oil',
            'vegetable oil',
            'sunflower oil',
            'rapeseed oil',
            'vinegar',
            'balsamic vinegar',
            'flour',
            'plain flour',
            'self raising flour',
            'self-raising flour',
            'bread flour',
            'sugar',
            'caster sugar',
            'icing sugar',
            'baking powder',
            'bicarbonate of soda',
            'yeast',
            'baking ingredients',
            'soy sauce',
            'fish sauce',
            'hot sauce',
            'sriracha',
            'curry paste',
            'thai curry paste',
            'mexican kit',
            'taco kit',
            'fajita kit',
            'enchilada kit',
            'indian sauce',
            'chinese sauce',
            'teriyaki sauce',
            'noodles',
            'egg noodles',
            'rice noodles',
            'ramen',
            'udon',
            'world foods',
          ],
        },
        {
          key: 'hot_drinks',
          label: 'Tea, Coffee & Hot Drinks',
          keywords: [
            'tea',
            'tea bags',
            'teabags',
            'breakfast tea',
            'earl grey',
            'green tea',
            'herbal tea',
            'peppermint tea',
            'coffee',
            'instant coffee',
            'ground coffee',
            'coffee beans',
            'coffee pods',
            'nescafe',
            'kenco',
            'dolce gusto',
            'nespresso pods',
            'hot chocolate',
            'cocoa',
            'malted drink',
            'horlicks',
            'ovaltine',
          ],
        },
        {
          key: 'drinks',
          label: 'Drinks',
          keywords: [
            'drinks',
            'soft drink',
            'soft drinks',
            'fizzy drink',
            'fizzy drinks',
            'soda',
            'pop',
            'cola',
            'diet cola',
            'zero cola',
            'coke',
            'coca cola',
            'coca-cola',
            'diet coke',
            'coke zero',
            'zero coke',
            'cherry coke',
            'pepsi',
            'diet pepsi',
            'pepsi max',
            'cherry pepsi',
            'pepsi cherry',
            'lime pepsi',
            'pepsi lime',
            'mango pepsi',
            'pepsi mango',
            'tropical pepsi',
            'pepsi tropical',
            'lemon pepsi',
            'pepsi lemon',
            'cherry pepsi max',
            'pepsi max cherry',
            'lime pepsi max',
            'pepsi max lime',
            'mango pepsi max',
            'pepsi max mango',
            'tropical pepsi max',
            'pepsi max tropical',
            'lemon pepsi max',
            'pepsi max lemon',
            'cherry coke',
            'coke cherry',
            'lime coke',
            'coke lime',
            'mango coke',
            'coke mango',
            'tropical coke',
            'coke tropical',
            'lemon coke',
            'coke lemon',
            'cherry coke zero',
            'coke zero cherry',
            'lime coke zero',
            'coke zero lime',
            'mango coke zero',
            'coke zero mango',
            'tropical coke zero',
            'coke zero tropical',
            'lemon coke zero',
            'coke zero lemon',
            'sprite',
            'sprite zero',
            'zero sprite',
            '7up',
            '7 up',
            'fanta',
            'dr pepper',
            'dr. pepper',
            'irn bru',
            'irn-bru',
            'vimto',
            'ribena',
            'lemonade',
            'cloudy lemonade',
            'limeade',
            'ginger ale',
            'tonic water',
            'sparkling water',
            'flavoured water',
            'bottled water',
            'energy drink',
            'energy drinks',
            'red bull',
            'monster',
            'lucozade',
            'sports drink',
            'sports drinks',
            'squash',
            'cordial',
          ],
        },
        {
          key: 'alcohol',
          label: 'Alcohol',
          keywords: [
            'alcohol',
            'alcoholic drinks',
            'booze',
            'beer',
            'lager',
            'ale',
            'stout',
            'ipa',
            'wine',
            'red wine',
            'white wine',
            'rose wine',
            'rosé wine',
            'prosecco',
            'champagne',
            'cava',
            'sparkling wine',
            'cider',
            'hard cider',
            'fruit cider',
            'whisky',
            'whiskey',
            'scotch',
            'bourbon',
            'rye whiskey',
            'irish whiskey',
            'jack daniels',
            'jack daniel\'s',
            'jack daniels whiskey',
            'jack daniel\'s whiskey',
            'jack daniels honey',
            'jack daniel\'s honey',
            'jack daniels fire',
            'jack daniel\'s fire',
            'jack daniels apple',
            'jack daniel\'s apple',
            'jack and coke',
            'rum',
            'vodka',
            'gin',
            'tequila',
            'brandy',
            'cognac',
            'liqueur',
            'baileys',
            'jagermeister',
            'jägermeister',
            'malibu',
            'archers',
            'sambuca',
            'kopparberg',
            'kopparberg cider',
            'kopparberg strawberry lime',
            'kopparberg strawberry and lime',
            'kopparberg mixed fruit',
            'kopparberg pear',
            'kopparberg mixed fruit tropical',
            'kopparberg strawberry pineapple',
            'kopparberg strawberry and pineapple',
            'kopparberg mango',
            'kopparberg raspberry',
            'kopparberg cherry',
            'kopparberg blueberry lime',
            'kopparberg blueberry and lime',
            'kopparberg rhubarb',
            'kopparberg sweet vintage apple',
            'kopparberg spiced apple',
            'kopparberg winter punch',
            'kopparberg alcohol free',
            'kopparberg non alcoholic',
            'kopparberg alcohol free strawberry lime',
            'kopparberg alcohol free strawberry and lime',
            'kopparberg alcohol free mixed fruit',
            'kopparberg alcohol free pear',
            'kopparberg gin',
            'kopparberg strawberry lime gin',
            'kopparberg strawberry and lime gin',
            'kopparberg passionfruit orange gin',
            'kopparberg passionfruit and orange gin',
            'kopparberg vodka',
            'kopparberg strawberry lime vodka',
            'kopparberg strawberry and lime vodka',
            'kopparberg lemon vodka',
            'kopparberg gin lemonade',
            'kopparberg gin and lemonade',
            'kopparberg strawberry lime gin lemonade',
            'kopparberg strawberry and lime gin and lemonade',
            'rekorderlig',
            'rekorderlig cider',
            'rekorderlig strawberry lime',
            'rekorderlig strawberry and lime',
            'rekorderlig wild berries',
            'rekorderlig mango raspberry',
            'rekorderlig mango and raspberry',
            'rekorderlig passionfruit',
            'rekorderlig peach raspberry',
            'rekorderlig peach and raspberry',
            'rekorderlig pineapple kiwi',
            'rekorderlig pineapple and kiwi',
            'rekorderlig blood orange',
            'rekorderlig pink lemon',
            'rekorderlig watermelon citrus',
            'rekorderlig watermelon and citrus',
            'rekorderlig blackberry blackcurrant',
            'rekorderlig blackberry and blackcurrant',
            'rekorderlig pear apple',
            'rekorderlig pear and apple',
            'rekorderlig non alcoholic',
            'rekorderlig non-alcoholic',
            'rekorderlig alcohol free',
          ],
        },
        {
          key: 'pasta',
          label: 'Pasta',
          keywords: [
            'pasta',
            'long pasta',
            'short pasta',
            'tube pasta',
            'shaped pasta',
            'filled pasta',
            'fresh pasta',
            'dry pasta',
            'spaghetti',
            'bucatini',
            'linguine',
            'fettuccine',
            'capellini',
            'angel hair',
            'penne',
            'rigatoni',
            'fusilli',
            'rotini',
            'macaroni',
            'elbows',
            'cavatappi',
            'manicotti',
            'farfalle',
            'bowties',
            'orecchiette',
            'little ears',
            'radiatore',
            'orzo',
            'ravioli',
            'tortellini',
            'gnocchi',
          ],
        },
      ],
    },
    {
      key: 'non_food_general',
      label: 'Non-Food & General Merchandise',
      order: 6,
      sections: [
        {
          key: 'clothing',
          label: 'Clothing',
          keywords: ['t shirt', 't-shirt', 'socks', 'underwear', 'school uniform', 'baby clothes', 'jeans', 'pyjamas'],
        },
        {
          key: 'household',
          label: 'Home / Household Goods',
          keywords: [
            'washing up liquid', 'detergent', 'fabric softener', 'bin bags', 'foil', 'cling film', 'baking paper', 'kitchen roll',
            'bleach', 'sponges', 'surface cleaner', 'disinfectant', 'laundry', 'dishwasher tablet', 'dishwasher tablets', 'rinse aid',
            'rubber gloves', 'cleaning spray', 'cleaning sprays', 'bathroom cleaner', 'kitchen cleaner', 'floor cleaner',
            'cloths', 'microfibre cloths', 'laundry detergent', 'washing powder', 'washing pods', 'bedding', 'pillow',
            'duvet', 'plate', 'mug', 'pan', 'frying pan', 'storage box',
          ],
        },
        {
          key: 'health_beauty',
          label: 'Pharmacy / Health & Beauty',
          keywords: [
            'paracetamol', 'ibuprofen', 'toothpaste', 'toothbrush', 'shampoo', 'conditioner', 'soap', 'body wash', 'deodorant',
            'razor', 'toilet roll', 'shaving foam', 'mouthwash', 'hand wash', 'face wash', 'sanitary', 'tampons', 'pads',
            'skincare', 'moisturiser', 'vitamins', 'plasters', 'toiletries', 'shower gel', 'shaving gel', 'shaving products',
            'medicine', 'basic medicines', 'cold and flu', 'cough syrup',
          ],
        },
        {
          key: 'baby',
          label: 'Baby Supplies',
          keywords: [
            'nappies',
            'diapers',
            'baby wipes',
            'wipes',
            'formula',
            'baby formula',
            'follow on milk',
            'follow-on milk',
            'baby shampoo',
            'baby wash',
            'baby lotion',
          ],
        },
        {
          key: 'electrical',
          label: 'Electrical Goods',
          keywords: ['toaster', 'kettle', 'dvd', 'batteries', 'light bulb', 'light bulbs', 'headphones', 'extension lead'],
        },
        {
          key: 'pet_supplies',
          label: 'Pet Supplies',
          keywords: ['cat food', 'dog food', 'litter', 'pet treats', 'bird seed', 'pet toy', 'pet shampoo'],
        },
        {
          key: 'seasonal',
          label: 'Seasonal Aisle',
          keywords: [
            'easter egg', 'easter eggs', 'christmas decorations', 'christmas', 'easter', 'halloween', 'valentines',
            'bbq', 'barbecue', 'bbq supplies', 'charcoal', 'firelighters', 'summer toys', 'garden games',
            'stationery', 'notebook', 'pens', 'toys', 'toy', 'middle aisle', 'special buys',
          ],
        },
      ],
    },
  ],
};
