import { describe, expect, it } from 'vitest';
import { UK_CONFIG } from './uk';

describe('UK config', () => {
  it('includes the baby food aisle', () => {
    const cupboard = UK_CONFIG.groups.find((group) => group.key === 'food_cupboard');
    const babyFood = cupboard?.sections.find((section) => section.key === 'baby_food');
    const cereal = cupboard?.sections.find((section) => section.key === 'cereal');
    const snacks = cupboard?.sections.find((section) => section.key === 'snacks');
    const tinnedJarred = cupboard?.sections.find((section) => section.key === 'tinned_jarred');
    const homeBaking = cupboard?.sections.find((section) => section.key === 'home_baking');
    const cookingIngredients = cupboard?.sections.find((section) => section.key === 'cooking_ingredients');
    const hotDrinks = cupboard?.sections.find((section) => section.key === 'hot_drinks');
    const drinks = cupboard?.sections.find((section) => section.key === 'drinks');
    const alcohol = cupboard?.sections.find((section) => section.key === 'alcohol');
    const nonFood = UK_CONFIG.groups.find((group) => group.key === 'non_food_general');
    const baby = nonFood?.sections.find((section) => section.key === 'baby');
    const freezers = UK_CONFIG.groups.find((group) => group.key === 'food_freezers');
    const frozenTreats = freezers?.sections.find((section) => section.key === 'frozen_ice_cream');
    const frozenFruit = freezers?.sections.find((section) => section.key === 'frozen_fruit');
    const frozenMeals = freezers?.sections.find((section) => section.key === 'frozen_meals');

    expect(UK_CONFIG.code).toBe('uk');
    expect(UK_CONFIG.measurement).toEqual({ unitSystem: 'metric', displayMode: 'metric' });
    expect(babyFood?.label).toBe('Baby Food');
    expect(babyFood?.keywords).toContain('baby rice');
    expect(cereal?.label).toBe('Cereal Aisle');
    expect(cereal?.keywords).toContain('weetos');
    expect(cereal?.keywords).toContain('crunch clusters');
    expect(snacks?.label).toBe('Snacks & Crisps');
    expect(snacks?.keywords).toContain('crisps');
    expect(snacks?.keywords).toContain('biscuits');
    expect(tinnedJarred?.label).toBe('Tinned & Jarred Goods');
    expect(tinnedJarred?.keywords).toContain('baked beans');
    expect(tinnedJarred?.keywords).toContain('tinned tomatoes');
    expect(tinnedJarred?.keywords).toContain('ketchup');
    expect(tinnedJarred?.keywords).toContain('dijon mustard');
    expect(tinnedJarred?.keywords).toContain('mayonnaise');
    expect(tinnedJarred?.keywords).toContain('marmite');
    expect(homeBaking?.label).toBe('Home Baking');
    expect(homeBaking?.keywords).toContain('eggs');
    expect(homeBaking?.keywords).toContain('plain flour');
    expect(homeBaking?.keywords).toContain('baking powder');
    expect(homeBaking?.keywords).toContain('cream of tartar');
    expect(homeBaking?.keywords).toContain('golden syrup');
    expect(homeBaking?.keywords).toContain('edible glitter');
    expect(homeBaking?.keywords).toContain('sultanas');
    expect(homeBaking?.keywords).toContain('custard powder');
    expect(cookingIngredients?.label).toBe('Cooking Ingredients & World Foods');
    expect(cookingIngredients?.keywords).toContain('liquid smoke');
    expect(cookingIngredients?.keywords).toContain('soy sauce');
    expect(cookingIngredients?.keywords).toContain('fajita kit');
    expect(hotDrinks?.label).toBe('Tea, Coffee & Hot Drinks');
    expect(hotDrinks?.keywords).toContain('tea bags');
    expect(hotDrinks?.keywords).toContain('coffee pods');
    expect(drinks?.label).toBe('Drinks');
    expect(drinks?.keywords).toContain('pepsi max');
    expect(drinks?.keywords).toContain('zero sprite');
    expect(drinks?.keywords).toContain('cherry pepsi max');
    expect(drinks?.keywords).toContain('lime coke zero');
    expect(alcohol?.label).toBe('Alcohol');
    expect(alcohol?.keywords).toContain('jack daniels');
    expect(alcohol?.keywords).toContain('kopparberg sweet vintage apple');
    expect(alcohol?.keywords).toContain('rekorderlig wild berries');
    expect(alcohol?.keywords).toContain('kopparberg strawberry and lime gin and lemonade');
    expect(frozenTreats?.keywords).toContain('ice lollies');
    expect(frozenFruit?.keywords).toContain('frozen summer fruits');
    expect(frozenFruit?.keywords).toContain('frozen cherries');
    expect(frozenMeals?.keywords).toContain('frozen garlic bread');
    expect(baby?.label).toBe('Baby Supplies');
    expect(baby?.keywords).toContain('nappies');
  });
});
