import st from './primitives.module.scss';
import { classNames } from '../lib/classNames';

export const p = {
  badgeRow: st['badge-row'],
  button: st.button,
  buttonActive: classNames(st.button, st['button-active']),
  buttonDanger: classNames(st.button, st['button-danger']),
  buttonFull: classNames(st.button, st['button-full']),
  buttonIcon: classNames(st.button, st['button-icon']),
  buttonIconSvg: st['button-icon-svg'],
  buttonLink: classNames(st.button, st['button-link']),
  buttonPrimary: classNames(st.button, st['button-primary']),
  buttonRow: st['button-row'],
  buttonPrimarySm: classNames(st.button, st['button-primary'], st['button-sm']),
  buttonSecondary: classNames(st.button, st['button-secondary']),
  buttonSm: classNames(st.button, st['button-sm']),
  debugTable: st['debug-table'],
  debugTableCompact: classNames(st['debug-table'], st['debug-table-compact']),
  emptyState: st['empty-state'],
  field: st.field,
  fieldCompact: classNames(st.field, st['field-compact']),
  fieldFull: classNames(st.field, st['field-full']),
  formGrid: st['form-grid'],
  inlineRow: st['inline-row'],
  input: st.input,
  layoutSplit: st['layout-split'],
  muted: st.muted,
  notice: st.notice,
  noticeError: classNames(st.notice, st['notice-error']),
  pageTitleWithStatus: st['page-title-with-status'],
  sectionGroup: st['section-group'],
  select: st.select,
  separator: st.separator,
  smallText: st['small-text'],
  srOnly: st['sr-only'],
  stack: st.stack,
  storyCanvas: st['story-canvas'],
  subtitle: st.subtitle,
  tableWrap: st['table-wrap'],
  textarea: st.textarea,
  title: st.title,
  titleMd: classNames(st.title, st['title-md']),
  titleRow: st['title-row'],
  titleSm: classNames(st.title, st['title-sm']),
  titleXs: classNames(st.title, st['title-xs']),
};
