import st from './primitives.module.scss';
import { classNames } from '../lib/classNames';

export const p = {
  badgeRow: st['badge-row'],
  button: st.button,
  buttonActive: classNames(st.button, st['button-active']),
  buttonDanger: classNames(st.button, st['button-danger']),
  buttonFull: classNames(st.button, st['button-full']),
  buttonIcon: classNames(st.button, st['button-icon']),
  buttonIconSvg: st['button-icon-svg'],
  buttonLink: classNames(st.button, st['button-link']),
  buttonPrimary: classNames(st.button, st['button-primary']),
  buttonRow: st['button-row'],
  buttonPrimarySm: classNames(st.button, st['button-primary'], st['button-sm']),
  buttonSecondary: classNames(st.button, st['button-secondary']),
  buttonSm: classNames(st.button, st['button-sm']),
  debugTable: st['debug-table'],
  debugTableCompact: classNames(st['debug-table'], st['debug-table-compact']),
  debugLinkRow: st['debug-link-row'],
  editPageHeader: classNames(st['title-row'], st['edit-page-header']),
  editPageHeaderCopy: st['edit-page-header-copy'],
  editResetAllButton: classNames(st.button, st['edit-reset-all-button']),
  editSaveActions: st['edit-save-actions'],
  emptyState: st['empty-state'],
  emptyStateStack: classNames(st['empty-state'], st.stack),
  field: st.field,
  fieldCompact: classNames(st.field, st['field-compact']),
  fieldFull: classNames(st.field, st['field-full']),
  formGrid: st['form-grid'],
  inlineRow: st['inline-row'],
  input: st.input,
  inputWide: classNames(st.input, st['input-wide']),
  konamiTouchActive: st['konami-touch-active'],
  konamiTouchTapStage: st['konami-touch-tap-stage'],
  layoutSplit: st['layout-split'],
  measurementModeControls: st['measurement-mode-controls'],
  muted: st.muted,
  notice: st.notice,
  noticeError: classNames(st.notice, st['notice-error']),
  pageTitleWithStatus: st['page-title-with-status'],
  pasteAutocompleteShell: st['paste-autocomplete-shell'],
  productSuggestionList: st['product-suggestion-list'],
  productSuggestionListCaret: classNames(st['product-suggestion-list'], st['product-suggestion-list-caret']),
  productSuggestionOption: st['product-suggestion-option'],
  productSuggestionOptionActive: classNames(st['product-suggestion-option'], st['product-suggestion-option-active']),
  productSuggestionSection: st['product-suggestion-section'],
  productSuggestionValue: st['product-suggestion-value'],
  routeEditButton: classNames(st.button, st['route-edit-button']),
  routeFilterInput: classNames(st.input, st['route-filter-input']),
  routePageHeader: classNames(st['title-row'], st['route-page-header']),
  routePageHeaderCopy: st['route-page-header-copy'],
  routeResetActions: st['route-reset-actions'],
  routeToolbar: st['route-toolbar'],
  routeToolbarGroup: st['route-toolbar-group'],
  routeToolbarRow: st['route-toolbar-row'],
  routeViewControls: st['route-view-controls'],
  sectionGroup: st['section-group'],
  select: st.select,
  selectChevronSvg: st['select-chevron-svg'],
  selectShell: st['select-shell'],
  selectWithIcon: classNames(st.select, st['select-with-icon']),
  separator: st.separator,
  smallText: st['small-text'],
  srOnly: st['sr-only'],
  stack: st.stack,
  statLabel: st['stat-label'],
  storyCanvas: st['story-canvas'],
  subtitle: st.subtitle,
  tableWrap: st['table-wrap'],
  textarea: st.textarea,
  title: st.title,
  titleMd: classNames(st.title, st['title-md']),
  titleRow: st['title-row'],
  titleSm: classNames(st.title, st['title-sm']),
  titleXs: classNames(st.title, st['title-xs']),
  warningActions: st['warning-actions'],
};
