export const COUNTRY_CODES = new Set(['be', 'ca', 'de', 'es', 'fr', 'it', 'mx', 'nl', 'ro', 'uk', 'us']);

export const SECTION_KEYS = new Set([
  'produce',
  'bakery_counter',
  'butcher_counter',
  'fishmonger_counter',
  'deli_counter',
  'chilled_milk_juice_cream',
  'chilled_cooked_meat',
  'chilled_fresh_meat',
  'chilled_ready_meals',
  'frozen_veg',
  'frozen_ice_cream',
  'frozen_fruit',
  'frozen_meals',
  'pasta',
  'cereal',
  'baby_food',
  'tinned_jarred',
  'home_baking',
  'cooking_ingredients',
  'hot_drinks',
  'seafood_counter',
  'pantry',
  'snacks',
  'drinks',
  'alcohol',
  'baby',
  'clothing',
  'household',
  'health_beauty',
  'electrical',
  'pet_supplies',
  'seasonal',
  'other',
]);
